#!/bin/bash
# MyApp
#
# description: bla bla

case $1 in
    start)
        /bin/bash /home/pi/ProjetNepal/ClientCentrifugeuse-start.sh
    ;;
    stop)
        /bin/bash /home/pi/ProjetNepal/ClientCentrifugeuse-stop.sh

    ;;
    restart)
        /bin/bash /home/pi/ProjetNepal/ClientCentrifugeuse-stop.sh
        /bin/bash /home/pi/ProjetNepal/ClientCentrifugeuse-start.sh
    ;;
esac
exit 0

